import type { Document, Collection, TeamMember } from './types';

const now = new Date().toISOString();
const yesterday = new Date(Date.now() - 86400000).toISOString();
const lastWeek = new Date(Date.now() - 7 * 86400000).toISOString();

export const seedTeamMembers: Record<string, TeamMember> = {
  'member-1': {
    id: 'member-1',
    name: 'Brian Hackett',
    email: 'brian@replay.io',
    role: 'owner',
    avatarColor: '#6366f1',
    initials: 'BH',
  },
  'member-2': {
    id: 'member-2',
    name: 'Sarah Chen',
    email: 'sarah@replay.io',
    role: 'editor',
    avatarColor: '#22c55e',
    initials: 'SC',
  },
  'member-3': {
    id: 'member-3',
    name: 'Marcus Rivera',
    email: 'marcus@replay.io',
    role: 'editor',
    avatarColor: '#f59e0b',
    initials: 'MR',
  },
  'member-4': {
    id: 'member-4',
    name: 'Priya Patel',
    email: 'priya@replay.io',
    role: 'viewer',
    avatarColor: '#ec4899',
    initials: 'PP',
  },
};

// Collections
export const seedCollections: Record<string, Collection> = {
  'col-engineering': {
    id: 'col-engineering',
    name: 'Engineering Roadmap',
    icon: '🚀',
    viewType: 'kanban',
    defaultView: 'kanban',
    kanbanPropertyId: 'prop-status',
    propertySchema: [
      {
        id: 'prop-status',
        name: 'Status',
        type: 'select',
        options: [
          { id: 'status-backlog', label: 'Backlog', color: '#94a3b8' },
          { id: 'status-inprogress', label: 'In Progress', color: '#3b82f6' },
          { id: 'status-review', label: 'In Review', color: '#f59e0b' },
          { id: 'status-done', label: 'Done', color: '#22c55e' },
        ],
      },
      {
        id: 'prop-assignee',
        name: 'Assignee',
        type: 'person',
      },
      {
        id: 'prop-priority',
        name: 'Priority',
        type: 'select',
        options: [
          { id: 'pri-low', label: 'Low', color: '#94a3b8' },
          { id: 'pri-medium', label: 'Medium', color: '#f59e0b' },
          { id: 'pri-high', label: 'High', color: '#ef4444' },
        ],
      },
      {
        id: 'prop-due',
        name: 'Due Date',
        type: 'date',
      },
    ],
    documents: ['doc-eng-1', 'doc-eng-2', 'doc-eng-3', 'doc-eng-4', 'doc-eng-5', 'doc-eng-6'],
    createdAt: lastWeek,
  },
  'col-meetings': {
    id: 'col-meetings',
    name: 'Meeting Notes',
    icon: '📝',
    viewType: 'table',
    defaultView: 'table',
    propertySchema: [
      {
        id: 'prop-meeting-date',
        name: 'Date',
        type: 'date',
      },
      {
        id: 'prop-meeting-type',
        name: 'Type',
        type: 'select',
        options: [
          { id: 'mt-standup', label: 'Standup', color: '#6366f1' },
          { id: 'mt-planning', label: 'Planning', color: '#3b82f6' },
          { id: 'mt-retro', label: 'Retrospective', color: '#22c55e' },
          { id: 'mt-1on1', label: '1:1', color: '#f59e0b' },
          { id: 'mt-allhands', label: 'All Hands', color: '#ec4899' },
        ],
      },
      {
        id: 'prop-attendees',
        name: 'Attendees',
        type: 'person',
      },
    ],
    documents: ['doc-meet-1', 'doc-meet-2', 'doc-meet-3', 'doc-meet-4', 'doc-meet-5'],
    createdAt: lastWeek,
  },
  'col-marketing': {
    id: 'col-marketing',
    name: 'Marketing Campaigns',
    icon: '📣',
    viewType: 'gallery',
    defaultView: 'gallery',
    kanbanPropertyId: 'prop-camp-status',
    propertySchema: [
      {
        id: 'prop-camp-status',
        name: 'Status',
        type: 'select',
        options: [
          { id: 'cs-draft', label: 'Draft', color: '#94a3b8' },
          { id: 'cs-active', label: 'Active', color: '#22c55e' },
          { id: 'cs-paused', label: 'Paused', color: '#f59e0b' },
          { id: 'cs-complete', label: 'Complete', color: '#6366f1' },
        ],
      },
      {
        id: 'prop-camp-channel',
        name: 'Channel',
        type: 'select',
        options: [
          { id: 'ch-email', label: 'Email', color: '#3b82f6' },
          { id: 'ch-social', label: 'Social', color: '#ec4899' },
          { id: 'ch-ads', label: 'Paid Ads', color: '#f59e0b' },
          { id: 'ch-content', label: 'Content', color: '#22c55e' },
        ],
      },
      {
        id: 'prop-camp-owner',
        name: 'Owner',
        type: 'person',
      },
      {
        id: 'prop-camp-budget',
        name: 'Budget',
        type: 'number',
      },
    ],
    documents: ['doc-mkt-1', 'doc-mkt-2', 'doc-mkt-3', 'doc-mkt-4', 'doc-mkt-5', 'doc-mkt-6'],
    createdAt: lastWeek,
  },
};

const engineeringContent = (title: string, body: string) => JSON.stringify({
  type: 'doc',
  content: [
    { type: 'heading', attrs: { level: 1 }, content: [{ type: 'text', text: title }] },
    { type: 'paragraph', content: [{ type: 'text', text: body }] },
    {
      type: 'bulletList',
      content: [
        { type: 'listItem', content: [{ type: 'paragraph', content: [{ type: 'text', text: 'Define requirements and acceptance criteria' }] }] },
        { type: 'listItem', content: [{ type: 'paragraph', content: [{ type: 'text', text: 'Design system architecture and data models' }] }] },
        { type: 'listItem', content: [{ type: 'paragraph', content: [{ type: 'text', text: 'Implementation and unit tests' }] }] },
        { type: 'listItem', content: [{ type: 'paragraph', content: [{ type: 'text', text: 'Code review and QA signoff' }] }] },
      ],
    },
  ],
});

export const seedDocuments: Record<string, Document> = {
  // Engineering Roadmap
  'doc-eng-1': {
    id: 'doc-eng-1',
    title: 'Session Recording Improvements',
    icon: '🎬',
    content: engineeringContent('Session Recording Improvements', 'Improve the fidelity and performance of session recordings to reduce overhead on recorded applications.'),
    collectionId: 'col-engineering',
    propertyValues: [
      { propertyId: 'prop-status', value: 'In Progress' },
      { propertyId: 'prop-assignee', value: 'member-1' },
      { propertyId: 'prop-priority', value: 'High' },
      { propertyId: 'prop-due', value: '2026-06-15' },
    ],
    createdAt: lastWeek,
    updatedAt: yesterday,
    createdBy: 'member-1',
    shares: [],
    order: 0,
  },
  'doc-eng-2': {
    id: 'doc-eng-2',
    title: 'Time Travel Debugger v2',
    icon: '⏱️',
    content: engineeringContent('Time Travel Debugger v2', 'Rebuild the time travel debugger with improved performance and a new UI that supports multi-thread debugging.'),
    collectionId: 'col-engineering',
    propertyValues: [
      { propertyId: 'prop-status', value: 'In Review' },
      { propertyId: 'prop-assignee', value: 'member-2' },
      { propertyId: 'prop-priority', value: 'High' },
      { propertyId: 'prop-due', value: '2026-05-30' },
    ],
    createdAt: lastWeek,
    updatedAt: now,
    createdBy: 'member-1',
    shares: [],
    order: 1,
  },
  'doc-eng-3': {
    id: 'doc-eng-3',
    title: 'Browser Extension Refactor',
    icon: '🔌',
    content: engineeringContent('Browser Extension Refactor', 'Refactor the browser extension to use Manifest V3 and improve reliability across all supported browsers.'),
    collectionId: 'col-engineering',
    propertyValues: [
      { propertyId: 'prop-status', value: 'Backlog' },
      { propertyId: 'prop-assignee', value: 'member-3' },
      { propertyId: 'prop-priority', value: 'Medium' },
      { propertyId: 'prop-due', value: '2026-07-01' },
    ],
    createdAt: lastWeek,
    updatedAt: lastWeek,
    createdBy: 'member-2',
    shares: [],
    order: 2,
  },
  'doc-eng-4': {
    id: 'doc-eng-4',
    title: 'API Performance Optimization',
    icon: '⚡',
    content: engineeringContent('API Performance Optimization', 'Profile and optimize the backend API to reduce p99 latency from 800ms to under 200ms.'),
    collectionId: 'col-engineering',
    propertyValues: [
      { propertyId: 'prop-status', value: 'Done' },
      { propertyId: 'prop-assignee', value: 'member-1' },
      { propertyId: 'prop-priority', value: 'High' },
      { propertyId: 'prop-due', value: '2026-05-01' },
    ],
    createdAt: lastWeek,
    updatedAt: yesterday,
    createdBy: 'member-1',
    shares: [],
    order: 3,
  },
  'doc-eng-5': {
    id: 'doc-eng-5',
    title: 'User Auth & SSO',
    icon: '🔒',
    content: engineeringContent('User Auth & SSO', 'Implement SSO via SAML 2.0 and OAuth 2.0 for enterprise customers.'),
    collectionId: 'col-engineering',
    propertyValues: [
      { propertyId: 'prop-status', value: 'In Progress' },
      { propertyId: 'prop-assignee', value: 'member-2' },
      { propertyId: 'prop-priority', value: 'High' },
      { propertyId: 'prop-due', value: '2026-06-30' },
    ],
    createdAt: lastWeek,
    updatedAt: now,
    createdBy: 'member-2',
    shares: [],
    order: 4,
  },
  'doc-eng-6': {
    id: 'doc-eng-6',
    title: 'Replay Protocol Documentation',
    icon: '📚',
    content: engineeringContent('Replay Protocol Documentation', 'Write comprehensive documentation for the Replay protocol to enable third-party integrations.'),
    collectionId: 'col-engineering',
    propertyValues: [
      { propertyId: 'prop-status', value: 'Backlog' },
      { propertyId: 'prop-assignee', value: 'member-3' },
      { propertyId: 'prop-priority', value: 'Low' },
      { propertyId: 'prop-due', value: '2026-08-01' },
    ],
    createdAt: lastWeek,
    updatedAt: lastWeek,
    createdBy: 'member-3',
    shares: [],
    order: 5,
  },

  // Meeting Notes
  'doc-meet-1': {
    id: 'doc-meet-1',
    title: 'Weekly Engineering Standup',
    icon: '☕',
    content: JSON.stringify({
      type: 'doc',
      content: [
        { type: 'heading', attrs: { level: 1 }, content: [{ type: 'text', text: 'Weekly Engineering Standup' }] },
        { type: 'heading', attrs: { level: 2 }, content: [{ type: 'text', text: 'Attendees' }] },
        { type: 'paragraph', content: [{ type: 'text', text: 'Brian, Sarah, Marcus, Priya' }] },
        { type: 'heading', attrs: { level: 2 }, content: [{ type: 'text', text: 'Updates' }] },
        { type: 'bulletList', content: [
          { type: 'listItem', content: [{ type: 'paragraph', content: [{ type: 'text', text: 'Session recording PR merged — 15% latency improvement' }] }] },
          { type: 'listItem', content: [{ type: 'paragraph', content: [{ type: 'text', text: 'Time travel debugger in review, targeting release next week' }] }] },
          { type: 'listItem', content: [{ type: 'paragraph', content: [{ type: 'text', text: 'SSO implementation started, working on SAML integration' }] }] },
        ]},
        { type: 'heading', attrs: { level: 2 }, content: [{ type: 'text', text: 'Action Items' }] },
        {
          type: 'taskList',
          content: [
            { type: 'taskItem', attrs: { checked: true }, content: [{ type: 'paragraph', content: [{ type: 'text', text: 'Merge recording optimizations' }] }] },
            { type: 'taskItem', attrs: { checked: false }, content: [{ type: 'paragraph', content: [{ type: 'text', text: 'Ship time travel v2 to staging' }] }] },
            { type: 'taskItem', attrs: { checked: false }, content: [{ type: 'paragraph', content: [{ type: 'text', text: 'Schedule SSO design review' }] }] },
          ],
        },
      ],
    }),
    collectionId: 'col-meetings',
    propertyValues: [
      { propertyId: 'prop-meeting-date', value: yesterday },
      { propertyId: 'prop-meeting-type', value: 'Standup' },
      { propertyId: 'prop-attendees', value: 'member-1' },
    ],
    createdAt: yesterday,
    updatedAt: yesterday,
    createdBy: 'member-1',
    shares: [],
    order: 0,
  },
  'doc-meet-2': {
    id: 'doc-meet-2',
    title: 'Q2 Planning Session',
    icon: '📅',
    content: engineeringContent('Q2 Planning Session', 'Review Q1 outcomes and set priorities for Q2. Align on engineering roadmap and marketing initiatives.'),
    collectionId: 'col-meetings',
    propertyValues: [
      { propertyId: 'prop-meeting-date', value: lastWeek },
      { propertyId: 'prop-meeting-type', value: 'Planning' },
      { propertyId: 'prop-attendees', value: 'member-1' },
    ],
    createdAt: lastWeek,
    updatedAt: lastWeek,
    createdBy: 'member-1',
    shares: [],
    order: 1,
  },
  'doc-meet-3': {
    id: 'doc-meet-3',
    title: 'All Hands — May 2026',
    icon: '🌍',
    content: engineeringContent('All Hands — May 2026', 'Company-wide all hands meeting covering product updates, financials, and team announcements.'),
    collectionId: 'col-meetings',
    propertyValues: [
      { propertyId: 'prop-meeting-date', value: lastWeek },
      { propertyId: 'prop-meeting-type', value: 'All Hands' },
      { propertyId: 'prop-attendees', value: 'member-1' },
    ],
    createdAt: lastWeek,
    updatedAt: lastWeek,
    createdBy: 'member-1',
    shares: [],
    order: 2,
  },
  'doc-meet-4': {
    id: 'doc-meet-4',
    title: 'Brian & Sarah 1:1',
    icon: '🤝',
    content: engineeringContent('Brian & Sarah 1:1', 'Weekly 1:1 between Brian and Sarah covering project status, blockers, and career development.'),
    collectionId: 'col-meetings',
    propertyValues: [
      { propertyId: 'prop-meeting-date', value: yesterday },
      { propertyId: 'prop-meeting-type', value: '1:1' },
      { propertyId: 'prop-attendees', value: 'member-2' },
    ],
    createdAt: yesterday,
    updatedAt: yesterday,
    createdBy: 'member-2',
    shares: [],
    order: 3,
  },
  'doc-meet-5': {
    id: 'doc-meet-5',
    title: 'Sprint Retrospective — Sprint 22',
    icon: '🔄',
    content: engineeringContent('Sprint Retrospective — Sprint 22', 'Team retrospective to reflect on what went well, what could be improved, and action items.'),
    collectionId: 'col-meetings',
    propertyValues: [
      { propertyId: 'prop-meeting-date', value: lastWeek },
      { propertyId: 'prop-meeting-type', value: 'Retrospective' },
      { propertyId: 'prop-attendees', value: 'member-3' },
    ],
    createdAt: lastWeek,
    updatedAt: lastWeek,
    createdBy: 'member-3',
    shares: [],
    order: 4,
  },

  // Marketing Campaigns
  'doc-mkt-1': {
    id: 'doc-mkt-1',
    title: 'Dev Tools Launch Campaign',
    icon: '🚀',
    coverImage: 'https://images.unsplash.com/photo-1551650975-87deedd944c3?w=400&h=200&fit=crop',
    content: engineeringContent('Dev Tools Launch Campaign', 'Multi-channel campaign to announce the new Replay DevTools integration with major IDEs.'),
    collectionId: 'col-marketing',
    propertyValues: [
      { propertyId: 'prop-camp-status', value: 'Active' },
      { propertyId: 'prop-camp-channel', value: 'Social' },
      { propertyId: 'prop-camp-owner', value: 'member-3' },
      { propertyId: 'prop-camp-budget', value: 25000 },
    ],
    createdAt: lastWeek,
    updatedAt: now,
    createdBy: 'member-3',
    shares: [],
    order: 0,
  },
  'doc-mkt-2': {
    id: 'doc-mkt-2',
    title: 'Q2 Email Newsletter',
    icon: '📧',
    coverImage: 'https://images.unsplash.com/photo-1563986768494-4dee2763ff3f?w=400&h=200&fit=crop',
    content: engineeringContent('Q2 Email Newsletter', 'Quarterly newsletter to subscribers featuring product updates, blog posts, and developer spotlights.'),
    collectionId: 'col-marketing',
    propertyValues: [
      { propertyId: 'prop-camp-status', value: 'Draft' },
      { propertyId: 'prop-camp-channel', value: 'Email' },
      { propertyId: 'prop-camp-owner', value: 'member-3' },
      { propertyId: 'prop-camp-budget', value: 5000 },
    ],
    createdAt: lastWeek,
    updatedAt: yesterday,
    createdBy: 'member-3',
    shares: [],
    order: 1,
  },
  'doc-mkt-3': {
    id: 'doc-mkt-3',
    title: 'GitHub Sponsors Campaign',
    icon: '💖',
    coverImage: 'https://images.unsplash.com/photo-1618477388954-7852f32655ec?w=400&h=200&fit=crop',
    content: engineeringContent('GitHub Sponsors Campaign', 'Campaign targeting open source maintainers to adopt Replay for bug reproduction.'),
    collectionId: 'col-marketing',
    propertyValues: [
      { propertyId: 'prop-camp-status', value: 'Complete' },
      { propertyId: 'prop-camp-channel', value: 'Content' },
      { propertyId: 'prop-camp-owner', value: 'member-3' },
      { propertyId: 'prop-camp-budget', value: 10000 },
    ],
    createdAt: lastWeek,
    updatedAt: lastWeek,
    createdBy: 'member-3',
    shares: [],
    order: 2,
  },
  'doc-mkt-4': {
    id: 'doc-mkt-4',
    title: 'Google Ads — Bug Reproduction',
    icon: '🎯',
    coverImage: 'https://images.unsplash.com/photo-1611162617213-7d7a39e9b1d7?w=400&h=200&fit=crop',
    content: engineeringContent('Google Ads — Bug Reproduction', 'Paid search campaign targeting developers searching for bug reproduction tools.'),
    collectionId: 'col-marketing',
    propertyValues: [
      { propertyId: 'prop-camp-status', value: 'Active' },
      { propertyId: 'prop-camp-channel', value: 'Paid Ads' },
      { propertyId: 'prop-camp-owner', value: 'member-3' },
      { propertyId: 'prop-camp-budget', value: 30000 },
    ],
    createdAt: lastWeek,
    updatedAt: now,
    createdBy: 'member-3',
    shares: [],
    order: 3,
  },
  'doc-mkt-5': {
    id: 'doc-mkt-5',
    title: 'Conference Sponsorship — React Summit',
    icon: '🎤',
    coverImage: 'https://images.unsplash.com/photo-1540575467063-178a50c2df87?w=400&h=200&fit=crop',
    content: engineeringContent('Conference Sponsorship — React Summit', 'Sponsorship and speaking slot at React Summit 2026 to reach frontend developers.'),
    collectionId: 'col-marketing',
    propertyValues: [
      { propertyId: 'prop-camp-status', value: 'Paused' },
      { propertyId: 'prop-camp-channel', value: 'Content' },
      { propertyId: 'prop-camp-owner', value: 'member-3' },
      { propertyId: 'prop-camp-budget', value: 20000 },
    ],
    createdAt: lastWeek,
    updatedAt: yesterday,
    createdBy: 'member-3',
    shares: [],
    order: 4,
  },
  'doc-mkt-6': {
    id: 'doc-mkt-6',
    title: 'Twitter/X Developer Outreach',
    icon: '🐦',
    coverImage: 'https://images.unsplash.com/photo-1611605698335-8b1569810432?w=400&h=200&fit=crop',
    content: engineeringContent('Twitter/X Developer Outreach', 'Organic social media campaign to build developer community presence on Twitter/X.'),
    collectionId: 'col-marketing',
    propertyValues: [
      { propertyId: 'prop-camp-status', value: 'Active' },
      { propertyId: 'prop-camp-channel', value: 'Social' },
      { propertyId: 'prop-camp-owner', value: 'member-3' },
      { propertyId: 'prop-camp-budget', value: 0 },
    ],
    createdAt: lastWeek,
    updatedAt: now,
    createdBy: 'member-3',
    shares: [],
    order: 5,
  },

  // Standalone pages
  'doc-welcome': {
    id: 'doc-welcome',
    title: 'Welcome to Replay Workspace',
    icon: '👋',
    content: JSON.stringify({
      type: 'doc',
      content: [
        { type: 'heading', attrs: { level: 1 }, content: [{ type: 'text', text: 'Welcome to Replay Workspace 👋' }] },
        { type: 'paragraph', content: [{ type: 'text', text: 'This is your team workspace. Use it to collaborate on documents, track projects, and share knowledge.' }] },
        { type: 'heading', attrs: { level: 2 }, content: [{ type: 'text', text: 'Quick Start' }] },
        { type: 'bulletList', content: [
          { type: 'listItem', content: [{ type: 'paragraph', content: [{ type: 'text', text: 'Create a new document with the + button in the sidebar' }] }] },
          { type: 'listItem', content: [{ type: 'paragraph', content: [{ type: 'text', text: 'Use / to open the command menu and insert blocks' }] }] },
          { type: 'listItem', content: [{ type: 'paragraph', content: [{ type: 'text', text: 'Press Cmd+K to search across all documents' }] }] },
          { type: 'listItem', content: [{ type: 'paragraph', content: [{ type: 'text', text: 'Browse collections for structured data views' }] }] },
        ]},
        { type: 'heading', attrs: { level: 2 }, content: [{ type: 'text', text: 'Collections' }] },
        { type: 'paragraph', content: [{ type: 'text', text: 'Collections are databases of documents. Switch between Table, Kanban, and Gallery views.' }] },
        { type: 'blockquote', content: [{ type: 'paragraph', content: [{ type: 'text', text: '💡 Tip: Try the Engineering Roadmap in Kanban view to see your team\'s work in progress.' }] }] },
      ],
    }),
    propertyValues: [],
    createdAt: lastWeek,
    updatedAt: lastWeek,
    createdBy: 'member-1',
    shares: [],
    order: 0,
  },
};
